"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const MAX_PER_POND=15, palette=["#c9b98f","#b9a8a4","#9eb5aa","#a5b1ba","#afa5b8","#baa98f","#aab39a"];
const cfg=window.GOPI_CONFIG||{}, cloud=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase);
const sb=cloud?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let state={user:null,ponds:[],notes:[],activePond:null,selectedNote:null,editing:null,raf:null,install:null};
const storeKey=()=>`gopi_${state.user?.id||"demo"}`;
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(el.t);el.t=setTimeout(()=>el.classList.remove("show"),2400)}
function escapeHtml(v){const d=document.createElement("div");d.textContent=v;return d.innerHTML}
function stamp(iso){return new Intl.DateTimeFormat("es-MX",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true}).format(new Date(iso)).replace(",","")}
function localLoad(){const saved=JSON.parse(localStorage.getItem(storeKey())||"null");state.ponds=saved?.ponds||[{id:uid(),name:"Pizarra 01",created_at:new Date().toISOString()}];state.notes=saved?.notes||[];state.activePond=saved?.activePond||state.ponds[0].id}
function localSave(){localStorage.setItem(storeKey(),JSON.stringify({ponds:state.ponds,notes:state.notes,activePond:state.activePond}))}
async function loadData(){if(!cloud){localLoad();return}const [{data:p,error:pe},{data:n,error:ne}]=await Promise.all([sb.from("ponds").select("*").order("created_at"),sb.from("notes").select("*").order("created_at")]);if(pe||ne)throw pe||ne;state.ponds=p||[];state.notes=n||[];if(!state.ponds.length){const {data,error}=await sb.from("ponds").insert({user_id:state.user.id,name:"Pizarra 01"}).select().single();if(error)throw error;state.ponds=[data]}state.activePond=state.ponds[0].id}
async function savePond(name){if(cloud){const {data,error}=await sb.from("ponds").insert({user_id:state.user.id,name}).select().single();if(error)throw error;state.ponds.push(data)}else{state.ponds.push({id:uid(),name,created_at:new Date().toISOString()});localSave()}}
async function saveNote(note){if(cloud){const row={user_id:state.user.id,pond_id:note.pond_id,title:note.title,body:note.body,color:note.color};if(note.id){const {data,error}=await sb.from("notes").update(row).eq("id",note.id).select().single();if(error)throw error;Object.assign(state.notes.find(n=>n.id===note.id),data)}else{const {data,error}=await sb.from("notes").insert(row).select().single();if(error)throw error;state.notes.push(data)}}else{if(note.id)Object.assign(state.notes.find(n=>n.id===note.id),note);else state.notes.push({...note,id:uid(),created_at:new Date().toISOString()});localSave()}}
async function removeNote(id){if(cloud){const {error}=await sb.from("notes").delete().eq("id",id);if(error)throw error}state.notes=state.notes.filter(n=>n.id!==id);localSave()}
async function moveNote(id,pond_id){if(cloud){const {error}=await sb.from("notes").update({pond_id}).eq("id",id);if(error)throw error}state.notes.find(n=>n.id===id).pond_id=pond_id;localSave()}
function showApp(){$("#authView").classList.add("hidden");$("#appView").classList.remove("hidden");updatePonds();showScreen("homeView")}
function showScreen(id){$("#homeView").classList.toggle("hidden",id!=="homeView");$("#pondView").classList.toggle("hidden",id!=="pondView");if(id==="pondView")renderFish();else cancelAnimationFrame(state.raf)}
function updatePonds(){const many=state.ponds.length>1;$("#singlePondBtn").classList.toggle("hidden",many);$("#pondSelectWrap").classList.toggle("hidden",!many);$("#pondSelect").innerHTML=state.ponds.map(p=>`<option value="${p.id}" ${p.id===state.activePond?"selected":""}>${escapeHtml(p.name)}</option>`).join("");const count=state.notes.filter(n=>n.pond_id===state.activePond).length;$("#noteTotal").textContent=`${count} / ${MAX_PER_POND}`;$("#pondList").innerHTML=state.ponds.map(p=>`<div class="pond-row"><span>${escapeHtml(p.name)}</span><small>${state.notes.filter(n=>n.pond_id===p.id).length} notas</small></div>`).join("")}
function openNote(note=null){state.editing=note;$("#noteFormTitle").textContent=note?"Editar nota":"Nueva nota";$("#noteTitle").value=note?.title||"";$("#noteBody").value=note?.body||"";counts();$("#noteDialog").showModal()}
function counts(){$("#titleCount").textContent=`${$("#noteTitle").value.length}/18`;$("#noteCount").textContent=`${$("#noteBody").value.length}/500`}
function renderFish(){cancelAnimationFrame(state.raf);const tank=$("#fishTank"),notes=state.notes.filter(n=>n.pond_id===state.activePond);tank.innerHTML="";$("#emptyPond").classList.toggle("hidden",notes.length>0);const box=tank.getBoundingClientRect();const actors=notes.map((n,i)=>{const b=document.createElement("button");b.className="fish";b.style.setProperty("--fish",n.color);b.style.background=n.color;b.style.width=`${Math.min(220,120+n.title.length*5)}px`;b.innerHTML=`<span>${escapeHtml(n.title)}</span>`;b.addEventListener("click",()=>viewNote(n));tank.appendChild(b);const w=Math.min(220,120+n.title.length*5),h=64;return{el:b,n,x:Math.random()*Math.max(1,box.width-w),y:Math.random()*Math.max(1,box.height-h),vx:(.18+Math.random()*.22)*(Math.random()>.5?1:-1),vy:(Math.random()-.5)*.22,w,h,i}});let last=performance.now();function frame(now){const dt=Math.min(2,(now-last)/16.67);last=now;for(const a of actors){a.x+=a.vx*dt;a.y+=a.vy*dt;if(a.x<=0||a.x+a.w>=box.width){a.vx*=-1;a.x=Math.max(0,Math.min(a.x,box.width-a.w))}if(a.y<=0||a.y+a.h>=box.height){a.vy*=-1;a.y=Math.max(0,Math.min(a.y,box.height-a.h))}a.el.classList.toggle("left",a.vx<0);a.el.style.left=`${a.x}px`;a.el.style.top=`${a.y}px`}for(let i=0;i<actors.length;i++)for(let j=i+1;j<actors.length;j++){const a=actors[i],b=actors[j];if(Math.abs((a.x+a.w/2)-(b.x+b.w/2))<(a.w+b.w)*.34&&Math.abs((a.y+a.h/2)-(b.y+b.h/2))<45){const loser=a.w<b.w?a:a.w>b.w?b:(new Date(a.n.created_at)>new Date(b.n.created_at)?a:b);loser.vy=Math.abs(loser.vy)+.35;loser.y=Math.min(box.height-loser.h,loser.y+5);a.vx*=-1;b.vx*=-1}}state.raf=requestAnimationFrame(frame)}state.raf=requestAnimationFrame(frame);updatePonds()}
function viewNote(n){state.selectedNote=n;$("#viewTitle").textContent=n.title;$("#viewBody").textContent=n.body;$("#viewDate").textContent=stamp(n.created_at);$("#moveNoteBtn").classList.toggle("hidden",state.ponds.length<2);$("#viewDialog").showModal()}
async function ensureSpace(){let here=state.notes.filter(n=>n.pond_id===state.activePond).length;if(here<MAX_PER_POND)return true;let available=state.ponds.find(p=>state.notes.filter(n=>n.pond_id===p.id).length<MAX_PER_POND);if(!available){const nums=state.ponds.map(p=>Number((p.name.match(/Pizarra (\d+)/i)||[])[1])).filter(Number.isFinite);const next=String(Math.max(1,...nums)+1).padStart(2,"0");await savePond(`Pizarra ${next}`);available=state.ponds.at(-1);toast(`${available.name} creada automáticamente`)}state.activePond=available.id;updatePonds();return true}
async function enterDemo(){state.user={id:"demo",email:"Modo local"};await loadData();showApp()}
$("#demoBtn").onclick=enterDemo;
$("#authForm").onsubmit=async e=>{e.preventDefault();if(!cloud)return toast("Configura Supabase o usa el modo de prueba");const {data,error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error)return toast(error.message);state.user=data.user;await loadData();showApp()};
$("#registerBtn").onclick=async()=>{if(!cloud)return toast("Configura Supabase para crear cuentas");const {error}=await sb.auth.signUp({email:$("#email").value,password:$("#password").value});toast(error?error.message:"Cuenta creada. Revisa tu correo para confirmarla.")};
$("#newNoteBtn").onclick=async()=>{await ensureSpace();openNote()};$("#pondAddBtn").onclick=async()=>{await ensureSpace();openNote()};$("#myPondBtn").onclick=()=>showScreen("pondView");$("#singlePondBtn").onclick=()=>showScreen("pondView");$("#homeBtn").onclick=()=>showScreen("homeView");$("#settingsBtn").onclick=()=>{updatePonds();$("#settingsDialog").showModal()};
$("#pondSelect").onchange=e=>{state.activePond=e.target.value;localSave();renderFish()};
$("#noteTitle").oninput=counts;$("#noteBody").oninput=counts;
$("#noteForm").onsubmit=async e=>{e.preventDefault();try{await saveNote({id:state.editing?.id,pond_id:state.editing?.pond_id||state.activePond,title:$("#noteTitle").value.trim(),body:$("#noteBody").value.trim(),color:state.editing?.color||palette[Math.floor(Math.random()*palette.length)]});$("#noteDialog").close();toast(state.editing?"Cambios guardados":"Nota guardada");renderFish()}catch(err){toast(err.message)}};
$("#editNoteBtn").onclick=()=>{$("#viewDialog").close();openNote(state.selectedNote)};
$("#deleteNoteBtn").onclick=()=>{$("#viewDialog").close();$("#confirmDialog").showModal()};
$("#confirmDeleteBtn").onclick=async()=>{try{await removeNote(state.selectedNote.id);$("#confirmDialog").close();toast("Nota borrada");renderFish()}catch(e){toast(e.message)}};
$("#moveNoteBtn").onclick=()=>{const choices=state.ponds.filter(p=>p.id!==state.selectedNote.pond_id);$("#moveSelect").innerHTML=choices.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join("");$("#viewDialog").close();$("#moveDialog").showModal()};
$("#confirmMoveBtn").onclick=async()=>{try{const id=$("#moveSelect").value;if(state.notes.filter(n=>n.pond_id===id).length>=MAX_PER_POND)return toast("Esa pizarra ya tiene 15 notas");await moveNote(state.selectedNote.id,id);$("#moveDialog").close();toast("Nota movida");renderFish()}catch(e){toast(e.message)}};
$("#addPondBtn").onclick=()=>$("#pondDialog").showModal();$("#pondForm").onsubmit=async e=>{e.preventDefault();let raw=$("#pondName").value.trim().replace(/^pizarra\s*/i,"");if(!raw)return;const name=`Pizarra ${raw}`;if(state.ponds.some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast("Esa pizarra ya existe");await savePond(name);$("#pondDialog").close();$("#pondName").value="";updatePonds();toast("Pizarra creada")};
$("#logoutBtn").onclick=async()=>{if(cloud)await sb.auth.signOut();location.reload()};$$('[data-close]').forEach(b=>b.onclick=()=>$("#"+b.dataset.close).close());
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.install=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(state.install){state.install.prompt();await state.install.userChoice;state.install=null;$("#installBtn").classList.add("hidden")}};
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
(async()=>{if(cloud){const {data}=await sb.auth.getSession();if(data.session){state.user=data.session.user;try{await loadData();showApp()}catch(e){toast(e.message)}}}else $("#authHelp").textContent="Modo local disponible. Agrega Supabase para usar la misma cuenta en varios dispositivos."})();
