"use strict";
let backGuardArmed=false;
const noteColors=["#c9b98f","#b9a8a4","#9eb5aa","#a5b1ba","#afa5b8","#baa98f","#aab39a"];
function noteUrl(text){try{const raw=text.trim();const value=/^www\./i.test(raw)?"https://"+raw:raw;const parsed=new URL(value);return (parsed.protocol==="http:"||parsed.protocol==="https:")?parsed.href:null}catch{return null}}
const baseLoadData=loadData;loadData=async function(){await baseLoadData();const old=state.ponds.filter(p=>/^Charco /i.test(p.name));for(const pond of old){pond.name=pond.name.replace(/^Charco /i,"Pizarra ");if(cloud){const {error}=await sb.from("ponds").update({name:pond.name}).eq("id",pond.id);if(error)throw error}}if(old.length&&!cloud)localSave()};
renderFish=function(){cancelAnimationFrame(state.raf);const board=$("#fishTank");const notes=state.notes.filter(n=>n.pond_id===state.activePond).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));board.innerHTML="";board.className="fish-tank notes-board";$("#emptyPond").classList.toggle("hidden",notes.length>0);notes.forEach((note,index)=>{const card=document.createElement("article");const url=noteUrl(note.body),size=note.body.length<60?"small":note.body.length<220?"medium":"large";card.className=`board-note ${size}${url?" is-link":""}`;card.style.setProperty("--paper",noteColors[index%noteColors.length]);const preview=url?"🔗 Abrir enlace":escapeHtml(note.body.slice(0,110))+(note.body.length>110?"…":"");card.innerHTML='<span class="pin" aria-hidden="true"></span><button class="note-hit"><strong>'+escapeHtml(note.title)+'</strong><span class="note-preview">'+preview+'</span><time>'+stamp(note.created_at)+'</time></button>'+(url?'<button class="note-manage" aria-label="Ver o editar nota">⋮</button>':"");card.querySelector(".note-hit").addEventListener("click",()=>{if(url)window.open(url,"_blank","noopener,noreferrer");else viewNote(note)});card.querySelector(".note-manage")?.addEventListener("click",()=>viewNote(note));board.appendChild(card)});updatePonds()};
const versionValue=[...document.querySelectorAll(".setting-row")].find(row=>row.textContent.includes("Versión"))?.querySelector("b");if(versionValue)versionValue.textContent="1.1.11";
const backgroundLabel=$("#backgroundSelect")?.closest("label");if(backgroundLabel)backgroundLabel.classList.add("hidden");
const hint=$(".turn-hint");if(hint)hint.textContent="Notas recientes primero";
const emptyTitle=$("#emptyPond b"),emptyText=$("#emptyPond span");if(emptyTitle)emptyTitle.textContent="El pizarrón está vacío";if(emptyText)emptyText.textContent="Crea una nota para colocarla aquí.";
$(".hero-fish").textContent="📝";$(".brand").innerHTML="🎓 <span>TableroGO</span>";$("#myPondBtn b").textContent="📌";
function armBackGuard(){if(backGuardArmed)return;history.pushState({gopionline:true},"");backGuardArmed=true}
const originalShowApp=showApp;showApp=function(){originalShowApp();armBackGuard()};
window.addEventListener("popstate",async()=>{if(!state.user)return;const openDialog=[...document.querySelectorAll("dialog[open]")].at(-1);if(openDialog){openDialog.close();history.pushState({gopionline:true},"");return}if(["pondView","qrView","messagesView"].some(id=>!$("#"+id)?.classList.contains("hidden"))){showScreen("homeView");history.pushState({gopionline:true},"");return}if(cloud)await sb.auth.signOut();state.user=null;$("#appView").classList.add("hidden");$("#authView").classList.remove("hidden");toast("Sesión cerrada");backGuardArmed=false});
if(!$("#appView").classList.contains("hidden"))armBackGuard();
